### ISSUE TITLE
Filter by segmentId

### ISSUE THREAD

**Issue by guilhermef** [tpitale/legato#100]
Hi, I'm trying to use the segment_id filter.
On garb I was just doing:
```
Clicks.results(profile, {:start_date => one_month_ago, :end_date => yesterday, :segment_id => '12129342342'})
```
But on Legato, it just ignores the segment_id param.

There's an undocumented way to pass this param ?

Thanks in advance.

**Comment by igrep** [comment]
You have to declare with `segment` method like `filter`:

```ruby
class NewVisitor
  extend Legato::Model
  segment(:new_visitor){ eql(:user_type, 'New Visitor'.freeze) }
end
```

But, I don't know how to specify `segment_id` as your Garb sample.

**Comment by guilhermef** [comment]
I've made a few changes to accommodate segment_id on the query params, I'll
do a pull request tomorrow.

**Comment by guilhermef** [comment]
@igrep I've made a few changes to support segment_id: #102
