### ISSUE TITLE
OAuth2::Error for `#web_property` on mobile app data profile

### ISSUE THREAD

**Issue by thmzlt** [tpitale/legato#104]
When iterating through my GA profiles to get the property names, once I hit a profile containing mobile app data, I get an `OAuth2::Error` when calling `#web_property` on that profile:

```ruby
[8] pry(#<MyApp>)> user.profiles[58].web_property
OAuth2::Error: {"errors"=>[{"domain"=>"global", "reason"=>"invalidValue", "message"=>"Value for field websiteURL = -- is not valid."}], "code"=>400, "message"=>"Value for field websiteURL = -- is not valid."}: 
{"error":{"errors":[{"domain":"global","reason":"invalidValue","message":"Value for field websiteURL = -- is not valid."}],"code":400,"message":"Value for field websiteURL = -- is not valid."}}
from /path/to/gems/ruby/2.1/gems/oauth2-1.0.0/lib/oauth2/client.rb:113:in `request'

```

**Comment by tpitale** [comment]
`Value for field websiteURL = -- is not valid.` … that's disconcerting. I'm guessing that's because it's mobile app data, and not a website.

I'll check, but my first guess is this is a google issue.

**Comment by tpitale** [comment]
Yeah … we don't make any request _using_ the website url. You can check here: https://github.com/tpitale/legato/blob/master/lib/legato/management/web_property.rb#L14

**Comment by tpitale** [comment]
The code you're using goes back **up** the tree, by the way. So you're hitting this code here: https://github.com/tpitale/legato/blob/master/lib/legato/management/web_property.rb#L47-L51. Probably not required.

Calling `user.profiles` get's all profiles across all web properties.

**Comment by tpitale** [comment]
You could ask on the forum here: https://productforums.google.com/forum/#!forum/analytics
