### ISSUE TITLE
Adding quotaUser parameter to management API calls ?

### ISSUE THREAD

**Issue by MGPalmer** [tpitale/legato#105]
Hi and first of all thanks for this gem! We're using it in a Rails app to display statistics to our users. We've been running into the quota exceeded errors, so we've added the quotaUser setting to the results calls as documented. However, due to the way we load the data (ajax call to our server -> Legato to GA), we need to set up the profile/account for each request and these calls also run into the quota limit.

I found no way to add the quotaUser parameter to the management API calls so I cobbled this together:

```
Legato::User.class_eval do
  attr_accessor :quota_user
end
Legato::Management::Finder.class_eval do
  alias_method :original_uri_for_user, :uri_for_user
  def uri_for_user(user, path)
    original = original_uri_for_user(user, path)
    uri = if user.quota_user
      p = "quotaUser=#{user.quota_user}"
      if original =~ /\?/
        original + "&#{p}"
      else
        original + "?#{p}"
      end
    else
      original
    end
#    puts "original: " + original
#    puts "overridden: " + uri
    uri
  end
end
```

I'd like to submit a pull request, however I'd love to have some guidance where the best place to put the accessor etc. would be...

**Comment by tpitale** [comment]
Can you share the GA docs for where quota user is on the management API?

**Comment by tpitale** [comment]
If it's the same as on other queries, we could make a change to support adding it on the User: https://github.com/tpitale/legato/blob/master/lib/legato/user.rb. I'd be happy to do that along at the same time I do #106.

**Comment by MGPalmer** [comment]
https://developers.google.com/analytics/devguides/config/mgmt/v3/limits-quotas

**Comment by MGPalmer** [comment]
For now my hack seems to work for us, so no hurry. If you're going to work on refactoring that anyway it sounds like a good combination to me :)

**Comment by tpitale** [comment]
I think I'm going to add both `userIP` and `quotaUser` to the `User` for use globally on all queries. I presume if you want to use it on management, you'll want to use it on queries.

**Comment by tpitale** [comment]
I should be able to make these changes today or tomorrow. If you don't hear back by then, just ping me. When I'm done, I'll ask you to test out a pre-release, if you wouldn't mind.

**Comment by MGPalmer** [comment]
Absolutely, that sounds great.
