### ISSUE TITLE
Apply realtime tracking scope to filters

### ISSUE THREAD

**Issue by ndnenkov** [tpitale/legato#114]
Calling `Model#realtime` doesn't change the tracking scope of its filters. For example:
```ruby
class TotalEventsByEventCategory
  extend Legato::Model

  metrics :totalEvents
  dimensions :eventCategory
  filter(:something) { matches(:eventCategory, 'Something') }
end

realtime_query = TotalEventsByEventCategory.results(profile).something.realtime
realtime_query.each { |row| puts row }
```

Will result in an error:
>"Unknown dimension(s): ga:eventCategory"

What I am currently doing is explicitly setting the tracking scope of filters before calling `each`:
```ruby
realtime_query.filters.each { |filter| filter.tracking_scope = 'rt' }
```

It doesn't feel right. Is there a better way to do this?

**Comment by tpitale** [comment]
That is … odd. I will take a look.

**Comment by tpitale** [comment]
Could you try master branch to see if your query works to your satisfaction? You should not have to set the filter tracking scope after having called `realtime` on a query.

**Comment by tpitale** [comment]
If it works as expected on master, I'll cut a new gem. Thanks for reporting.

**Comment by ndnenkov** [comment]
Still getting the same error.

**Comment by tpitale** [comment]
Oh, I know why it's not working now. If you make the `realtime` call first, before the filter:

```ruby
TotalEventsByEventCategory.realtime.results(profile).something
```

I will open a new ticket to make it so you can call realtime at any point in the query chain.

**Comment by tpitale** [comment]
If you could try updating from master again. I've merged #117 to fix the ordering of the call to realtime.

**Comment by ndnenkov** [comment]
It works now. Thanks!

**Comment by tpitale** [comment]
Great! I'll release a gem shortly.

**Comment by tpitale** [comment]
Release v0.7.0.
