### ISSUE TITLE
Handle users with > 1000 profiles

### ISSUE THREAD

**Issue by proby** [tpitale/legato#12]
We just ran across this with one of our customers. They have more than 1000 GA profiles associated with their account.  For this user the `all` method in `finder.rb` would only get the first 1000 profiles.

It's quite an edge case, potentially not worth fixing, but I thought you might want to know it exists in the wild.

**Comment by tpitale** [comment]
Seems like someone else wants this. I'll take a look at adding.

**Comment by tpitale** [comment]
https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/profiles/list#response

Looks like a paginated list is the only option. Doesn't seem like we can pass a larger number to `max-results`

**Comment by mocerinoj** [comment]
@tpitale Thats correct, you would have to loop through each page of results.

As a workaround for now, I am inputing the profile id (view id) manually into my app for accounts that do not show up in `ga.profiles`.. I have been using `profile = ga.profiles.select {|profile| profile.id == account_domain.profile_id.to_s}` to select a specific profile.. but this relies on getting all the profiles first.  Is there a way to select a profile with a supplies profile id without selecting from `.profiles`?
