### ISSUE TITLE
problem with event conversion rates

### ISSUE THREAD

**Issue by nfriend21** [tpitale/legato#120]
I have discovered that when a Google Analytics Conversion Goal is an "Event" (i.e. not a Destination), we are unable to query the results.  

I am able to see conversion data within GA for these goals.  But when I use Legato to try to see them, it always returns a 0% result.  In contrast, the Destination goals always work perfectly.  

for example:

```

class LegatoSourceMediumConversions

  extend Legato::Model

  metrics :sessions, :goal1ConversionRate, :goal14ConversionRate

  dimensions :sourceMedium, :hostname

  filter(:for_hostname) { |hostname| matches(:hostname, hostname) }

end
```

In the above code, the :goal1ConversionRate is a destination goal and returns data no problem.  The :goal14ConversionRate is an event goal, and always returns 0%, even though when you look in GA, the conversion rate actually exists.

**Comment by tpitale** [comment]
There are no guarantees that the API returns the same data as is visible in the UI. I would start by checking the documentation for the GA API to determine if these metrics/dimensions are supported with event data?

Is there some reason you feel that this particular data difference is an issue within Legato?

In the future, please include information about which version of Ruby/Legato you are using, along with an example of your usage (not just the class).
