### ISSUE TITLE
Adding metrics to Legato::Model

### ISSUE THREAD

**Issue by 5t111111** [tpitale/legato#122]
It is possible to add metrics to a class which extends `Legato::Model` by invoking `.metrics(:metric_to_add)` on it. However, since metrics are defined as class instance variables, once metrics are added, they remain until restarting process, and eventually they causes an API error by exceeding limitation.

I am having trouble with this behavior because I re-use a class and I have to dynamically add metrics for completions of the goals taken from Management API to it.

For a workaround, I am going to re-initialize a class via kind of `Klass.instance_variable_set(:@metrics, nil)` once that class is used.

Are there any other way to "add metrics dynamially" and also "remove them safely once after they are used" ?

**Comment by tpitale** [comment]
Legato is intended to be used to model the queries you make as reports (thus the name `Legato::Model`). I would suggest using it as intended https://github.com/tpitale/legato#google-analytics-model and designing your usage. It is not intended, nor advised, to make only ad hoc calls.

**Comment by tpitale** [comment]
You're probably better off with something like:

```ruby
single_use_class = Class.new do
  extend Legato::Model
  metrics :whatever
end
instance = single_use_class.new
# etc
```

**Comment by 5t111111** [comment]
Thanks! I will do as you suggest. Taking into account exclusive control was a pain...
