### ISSUE TITLE
Provide directions for JSON format credentials

### ISSUE THREAD

**Issue by jcoyne** [tpitale/legato#124]
When creating a new account, Google steers you toward downloading the credentials as a JSON file:

<img width="495" alt="screen shot 2016-06-10 at 3 44 35 pm" src="https://cloud.githubusercontent.com/assets/92044/15978276/adad7b0e-2f22-11e6-9fe9-048ab6a91f88.png">

it would be great to have updated directions for using the gem with this format.

**Comment by tpitale** [comment]
Is that for a service account?

**Comment by tpitale** [comment]
@jcoyne Can you share the format with your private data removed?

**Comment by tpitale** [comment]
I think the wiki provides the information you need: https://github.com/tpitale/legato/wiki/OAuth2-and-Google#application-code
