### ISSUE TITLE
Programatically get a token

### ISSUE THREAD

**Issue by MatthiasRMS** [tpitale/legato#125]
On this page: https://github.com/tpitale/legato/wiki/OAuth2-and-Google, it is written:

token = 'A_TOKEN_I_ALREADY_HAVE'

I managed to get a token manually, which is good for 30 minutes. But how am I supposed to get this to work in production ? I can't get a token manually from http://localhost?code=########  each time I need to see my google analytics statitics. Is there a workaround ? How do you proceed ?

**Comment by tpitale** [comment]
I think what you want is a Service Account. Check this page in the wiki: https://github.com/tpitale/legato/wiki/OAuth2-and-Google
