### ISSUE TITLE
Http Request count for GA API 

### ISSUE THREAD

**Issue by wrocla** [tpitale/legato#128]
I would like to count (each profile)Http Request count for Google Analytics API.

And a issue is warned and http requests is stoped when exceeding the limit.

**Comment by tpitale** [comment]
I … don't think this is something I'd like to add to legato. GA already stops requests (or errors) when you cross their per-profile limit, IIRC.

It's possible you could leverage or implement rate-limiting in the underlying oauth or http libraries.
