### ISSUE TITLE
Getting sessions for a specific day

### ISSUE THREAD

**Issue by pezholio** [tpitale/legato#129]
Apologies for the basic question, but I've been banging my head against a brick wall for hours, and I don't know where else to turn. I'm trying to get some basic analytics from GA to display on a dashboard, namely the number of sessions in the last hour. I have a very simple metric set up like so:

```ruby
class Sessions
  extend Legato::Model

  metrics :sessions
end
```

And I'm trying to get the results like so:

```ruby
user = Legato::User.new GoogleOauth2Installed.access_token
profile = user.profiles.find { |p| p.web_property_id == "UA-XXXXXXX-1" }
profile.sessions(start_date: DateTime.now.prev_day, end_date: DateTime.now).total_results
#=> 1
```

Looking at my GA dashboard, I expect the last call to be returning much more than just`1` (it's more like 19k), but I'm clearly missing something. Any ideas?

**Comment by tpitale** [comment]
The API does not guarantee the data returned is the same as in the UI. The problem is likely in their processing of your data. There is often a delay.

You _may_ be able to use the realtime API to get data this recent. But the realtime API does not necessarily support ALL functionality.

**Comment by pezholio** [comment]
I've amended this to get results between one day ago at midnight and today at midnight, and I still get the result `1`:

```ruby
profile.sessions(
  start_date: DateTime.now.prev_day.beginning_of_day, 
  end_date: DateTime.now.beginning_of_day
).total_results
#=> 1
```

Am I doing something wrong? I find GA confusing at the best of times, so sure I'm missing something.

**Comment by tpitale** [comment]
Try a day from like a week ago.

**Comment by tpitale** [comment]
@pezholio Did that work?
