### ISSUE TITLE
Accessing GA segments

### ISSUE THREAD

**Issue by wrydere** [tpitale/legato#130]
In GA I have set up a variety of custom segments. Many of these involve chaining together events ("sequences") so that I can get visibility into high-conversion funnels, like so:

![image](https://user-images.githubusercontent.com/1455616/26890004-de32cd56-4b64-11e7-93a2-ee1326e23a43.png)

I'm curious if it is possible to access these segments via Legato. Or perhaps use a custom query to access them. Using Query Explorer I can find the ID's of the segments:

![image](https://user-images.githubusercontent.com/1455616/26890033-0d9649e2-4b65-11e7-9eb8-6dc34544d969.png)

Or I can also use Query Explorer to convert the segment with sequence into a query syntax:

`users::sequence::ga:pagePath==/;ga:eventLabel[]Get Started (Top Nav)|Contact Sales (Above Footer)|Get Started (Above Footer)|Get Started (Home Hero);->>ga:eventLabel[]Funnel Step 2;ga:eventAction[]Submitted`

I've tried  this using filters and segments in my Legato::Model classes without luck. For reference here is a complete Query Explorer query that would use a custom segment ID:

`https://www.googleapis.com/analytics/v3/data/ga?ids=ga%3A{redacted}&start-date=30daysAgo&end-date=yesterday&metrics=ga%3Asessions&dimensions=ga%3AeventAction&segment=gaid%3A%3AoBlBxRz5QN-8aMERVYap4w`

I am thinking that maybe the missing piece of the puzzle would be related to this page: https://github.com/tpitale/legato/wiki/Management:-Goals-&-Segments

Thanks for any guidance!

**Comment by tpitale** [comment]
I think you'll probably want to use the `segment_id`. I've made a commit to the README to add mention of how to do this, previously missing from any docs (my bad!).

https://github.com/tpitale/legato/commit/e992f17d86e4b9bf74308e62735b47f831ca6a2f

Note: cannot mix `segment_id` with other defined `segments`, the ID will supersede any others on the query.

Let  me know if that is enough info! I can also add to that blank wiki page.

**Comment by wrydere** [comment]
_Yes!_ That was the missing bit of information I needed. Thank you very much. Even simpler than I anticipated.
