### ISSUE TITLE
Is this gem still being maintained?

### ISSUE THREAD

**Issue by curtp** [tpitale/legato#135]
Looks like Google has updated the API to version 4.0.  Any plans for updating the gem to use the new version of the API?

**Comment by tpitale** [comment]
Yes. I just haven't gotten to it yet.

**Comment by tpitale** [comment]
Also, version 3 is still supported by google.

**Comment by curtp** [comment]
Excellent!  We're going to be building a lot more integrations using your gem and wanted to double check before going too far.

Thanks

**Comment by tpitale** [comment]
If you'd like V4 support, open an issue for that and I'll try to tackle it asap. Thanks!

**Comment by curtp** [comment]
No rush.  We'll migrate to the new version when it is ready.  Thanks!
