### ISSUE TITLE
Use the Account Summary API to populate Account and Profile List

### ISSUE THREAD

**Issue by sunil221** [tpitale/legato#71]
Is there are any way using which we can connect to the account summary API. Benefit of Account Summary API is that all accounts, properties and profiles are pulled in one query, then a tree can be built locally based on this queried result.

Link: https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtAccountSummariesGuide

Can we connect this using legato gem?

**Comment by tpitale** [comment]
Resolved in #101
