### ISSUE TITLE
Authentication fails?

### ISSUE THREAD

**Issue by cboettig** [tpitale/legato#80]

**Comment by osnysantos** [comment]
I'm facing this same problem, exactly as @cboettig  said. Every time I have to get a new token so I continue testing.

**Comment by tpitale** [comment]
I'm able to run the wiki code. Do you have the correct settings in google to enable analytics access for your oauth info?

**Comment by tpitale** [comment]
<img width="455" alt="screen shot 2015-11-11 at 10 23 48 am" src="https://cloud.githubusercontent.com/assets/163/11094564/61b520dc-885e-11e5-914b-3b4d0456c50d.png">

**Comment by osnysantos** [comment]
I think so because I can see my GA data, but just at first request, refreshing the page I get this error:

```
OAuth2::Error (invalid_grant: Code was already redeemed.
  {
    "error" : "invalid_grant",
    "error_description" : "Code was already redeemed."
  }):
```

My code is exactly as wiki. For every request I have to hit the address on browser to copy the new auth code.

![image](https://cloud.githubusercontent.com/assets/710567/11096484/7930457a-8881-11e5-8ad5-64b2647a4d68.png)

**Comment by tpitale** [comment]
That code is a single use. You get an access token with it. That access token may be used for 30 minutes before needing refreshing.

I would advise reading up on how to use OAuth 2. This is not a Legato issue. The wiki is only a short primer.

**Comment by tpitale** [comment]
I've updated the wiki: https://github.com/tpitale/legato/wiki/OAuth2-and-Google To add _more_ caveats about how this is not a definitive guide to OAuth 2, and how you need to understand how that process works before using any tool that works with Google (or any of the many other services that auth using OAuth 2).
