### ISSUE TITLE
Use tracking_scope on query to prefix metrics/dimensions/sort

### ISSUE THREAD

**Issue by tpitale** [tpitale/legato#92]
Rather than setting tracking scope on metrics/dimensions directly in the model, let the model be flexible enough to use query realtime to know the tracking scope prefix.

**Comment by tpitale** [comment]
Change inspired by https://github.com/tpitale/legato/issues/91

**Comment by Thermatix** [comment]
I don't want to be rude about this but when will this be implemented?

**Comment by tpitale** [comment]
Seriously? I just said on your ticket I'm doing it right now …

**Comment by Thermatix** [comment]
That's why I said I don't want to be rude, I really don't, but I really need to get this (what I'm working on) finished so If I could have a time frame (even if it's just something vague like tomorrow) I can at least say to my boss that I can finish this by so and so time.

**Comment by tpitale** [comment]
But it is rude. Whether you want it to be or not. I've been extremely responsive this whole time, for this FREE and OPEN SOURCE software. I gave you a resolution in the other ticket and I just published a PR.

If you want it done sooner than right this second, you're always welcome to submit your own PR.

**Comment by tpitale** [comment]
At this point, it'll be done as soon as Travis CI finishes running … I can't make it go any faster.

**Comment by Thermatix** [comment]
I know that and I'm grateful for your quick responses, I'd spent a few hours trying to figure out what the problem was so I'm extremely grateful that you quickly helped to resolve the issue.

You know what, never mind, I'll just wait till tomorrow as I'm about to leave work. 

Again though, thanks for the quick response.
