### ISSUE TITLE
Why not Legato::User#segments and Legato::User#goals?

### ISSUE THREAD

**Issue by igrep** [tpitale/legato#97]
Sorry if I got something wrong. I'm new to this gem and Google Analytics.

Why not implement `Legato::User#segments` and `Legato::User#goals` like this?

```ruby
def segments
  Management::Segment.all(self)
end

def goals
  Management::Goal.all(self)
end
```

If you've just forgot, I'll send a PR.

**Comment by tpitale** [comment]
Just never did it … no real reason.

**Comment by tpitale** [comment]
A PR would be most welcome. Thank you!
