### ISSUE TITLE
How to define "Tablet and Desktop Traffic" segment on a Legato model

### ISSUE THREAD

**Issue by adlersantos** [tpitale/legato#99]
Hi guys! I just wanted to ask how to apply a segment to a specific Legato model. 

From the [`Legato::Model` source](https://github.com/tpitale/legato/blob/3c3cdb61ba4471203119f7b453654149be814ddd/lib/legato/model.rb), the `Legato::Model#segment` takes a name, and a block which contains filter methods to define the parameters used for segmenting the request to GA

I have the following code on my model:

```ruby
class BounceRate
  extend Legato::Model

  metrics :bouncerate
  dimensions :date, :deviceCategory

  # This returns OpenStruct instances but the tablet and desktop traffic are still separated
  filter(:tablet_desktop) { [matches(:deviceCategory, 'tablet'), matches(:deviceCategory, 'desktop')] }

  segment(:tablet_desktop_traffic) { 
    # what do we put in this block?
  }
end
```

What filter methods should I include in the block where the segment `:tablet_desktop_traffic` was defined?

Also, via the Google Analytics API docs, is it possible to directly use the segment via its `segmentId` without using any filters?

Thanks a lot! :)

**Comment by tpitale** [comment]
The data is split by the `deviceCategory` because you have that as a `dimension`. Dimensions are how the data is kind of "partitioned" (for lack of a better term).

`segment` should be defined the same way as a filter, but cannot be the same name as it results in method conflicts.

We used to have support for segment id but it was broken by a change in GA. I have not yet restored this feature.

**Comment by adlersantos** [comment]
We got it working. We removed the `:deviceCategory` under the list of dimensions, then we defined our segment as

```ruby
segment(:tablet_desktop) { [matches(:deviceCategory, 'tablet'), matches(:deviceCategory, 'desktop')] }
```

This now gives us results for the "Tablet and Desktop Traffic" segment. Thank you so much!
